# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = {
"Uha1" => "192.168.55.101",
"Uha2" => "192.168.55.102",
"Uweb1" => "192.168.55.103",
"Uweb2" => "192.168.55.104"
}

Vagrant.configure("2") do |config|
#выбираем образ системы
  config.vm.box = "ubuntu/jammy64"
#задаем провайдера и параметры вм 
 hosts.each do |name, ip|
  config.vm.define name do |vhost|
    vhost.vm.hostname = name
    vhost.vm.network "private_network", ip: ip
    vhost.vm.provider "virtualbox" do |vb|
	  vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.name = name
      vb.gui = false
      vb.memory = "512"
      vb.cpus = 1
    end
   end
#переносим открытый ключ на вм
  config.vm.provision "file", source: "me.pub", destination: "~/.ssh/me.pub" 
#ставим docker
  config.vm.provision "shell", inline: <<-SHELL
    apt-get install -y ca-certificates curl gnupg lsb-release
    mkdir -m 0755 -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update -y
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
#добавляем открытый ключ пользователям vagrant и root
	cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
	cat /home/vagrant/.ssh/me.pub >> /root/.ssh/authorized_keys
    SHELL
 end
end