# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = {
"ha1" => "192.168.55.101",
"ha2" => "192.168.55.102",
"web1" => "192.168.55.103",
"web2" => "192.168.55.104"
}

Vagrant.configure("2") do |config|
#выбираем образ системы
  config.vm.box = "centos/7"
#задаем провайдера и параметры вм 
 hosts.each do |name, ip|
  config.vm.define name do |vhost|
    vhost.vm.hostname = name
    vhost.vm.network "private_network", ip: ip
    vhost.vm.provider "virtualbox" do |vb|
      vb.name = name
      vb.gui = false
      vb.memory = "512"
      vb.cpus = 1
    end
   end
#переносим открытый ключ на вм
  config.vm.provision "file", source: "me.pub", destination: "~/.ssh/me.pub" 
#ставим docker
  config.vm.provision "shell", inline: <<-SHELL
    yum install -y yum-utils
	yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
	yum install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
#добавляем открытый ключ пользователям vagrant и root
	cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
	mkdir /root/.ssh
	cat /home/vagrant/.ssh/me.pub >> /root/.ssh/authorized_keys
    SHELL
 end
end
